name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  go_router: ^4.2.8
  intl: ^0.17.0
  json_annotation: ^4.6.0
  skeletons: ^0.0.3
  supabase: ^0.3.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - .env
